Creates unit test for trials call
UofS-Pulse-Binfo/tripal_ws_brapi pull request #65
Opened 2021-01-29 19:03 UTC by reynoldtan

2021-01-29 22:36 UTC, laceysanderson requested changes
Code Changes ❌ 
 - Studies are not being added to the trial properly

Check in the Browser:
 - Structure matches Apiary 
     - active is the wrong type. should be true ❌ 
 - Returns results using test data ✅
 - Check parameters
     - commonCropName ✅
     - programDbId ✅
     - missing parameters were not tested ❌ 
 
Test Review:
 - Tests all parameters ❌ 
     - Missing locationDbId, active, sortBy, sortOrder
 - Includes correct data structure and data types based on Apiary
     - Active should be a boolean ❌ 

There should be example data for studies within a trial ❌ 

Tests Pass ✅

2021-01-29 22:36 UTC, laceysanderson commented on calls/v1/trials/TripalWebServiceBrapiV1Trials.inc
> +        $project->studies = (array) ['set' => $all_studies];
This line makes no sense... Casting an associative array as an array will accomplish nothing... instead $all_studies should be an array of objects and used directly.

2021-02-01 16:37 UTC, reynoldtan commented
There should be example data for studies within a trial
Try host/web-services/brapi/v1/trials?pageSize=10&page=3

2021-02-01 18:14 UTC, laceysanderson commented
Great. This shows that your implementation is not the correct format.
<img width="1045" alt="Screen Shot 2021-02-01 at 12 09 42 PM" src="https://user-images.githubusercontent.com/1566301/106499738-91d54300-6486-11eb-8e87-b43ccac7b571.png">
<img width="371" alt="Screen Shot 2021-02-01 at 12 09 14 PM" src="https://user-images.githubusercontent.com/1566301/106499739-926dd980-6486-11eb-905c-9341f8ceeec6.png">

As I mentioned in my comment 'studies' should be an array of objects. Thus, $all_studies should be an array of objects and used directly. There is also incorrect names (i.e. `location` ), capitalization (i.e. `studydbid`), and fields (i.e. `phenotype_id`).

2021-02-01 18:59 UTC, reynoldtan commented
I understand the structure of studies, this is the result from my end. Could you please clear your cache and give it a quick refresh? 
![Screen Shot 2021-02-01 at 12 50 18 PM](https://user-images.githubusercontent.com/15472253/106504885-25117700-648d-11eb-9605-55d51500d9a6.png)
.

2024-06-27 17:33 UTC, merged